// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wctoouoaxbokkzhrvkhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjdG9vdW9heGJva2t6aHJ2a2htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDExMTQsImV4cCI6MjA3NTQ3NzExNH0.DllMvGhl5Uk9ryZ0G78uHTEWhkqaE-WV0cmXQUqUQIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});